"""Shared helpers for the Phase 5 experiment runners (implementation.md §5.3).

Used by ``scripts/run_sweep.py`` and ``scripts/run_ablation.py`` to turn a
sweep YAML (base_config + dotted-key grid) into per-run config files and
train/eval command lines.
"""

from __future__ import annotations

import copy
import itertools
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def load_yaml(path: str | Path) -> dict[str, Any]:
    """Load a YAML file; raises with a clear message on missing/invalid files."""
    path = Path(path)
    if not path.is_absolute():
        path = REPO_ROOT / path
    if not path.exists():
        raise FileNotFoundError(f"YAML not found: {path}")
    with open(path) as f:
        cfg = yaml.safe_load(f)
    if not isinstance(cfg, dict):
        raise ValueError(f"{path} must contain a YAML mapping at top level")
    return cfg


def set_dotted(cfg: dict[str, Any], dotted: str, value: Any) -> None:
    """Set ``cfg["a"]["b"]["c"] = value`` for ``dotted == "a.b.c"``.

    Creates intermediate dicts as needed (a sweep override for a section the
    base config does not have yet, e.g. ``fed.proximal_mu`` on a config whose
    ``fed`` section exists but lacks the key, is fine).
    """
    keys = dotted.split(".")
    node = cfg
    for k in keys[:-1]:
        if k not in node or not isinstance(node[k], dict):
            node[k] = {}
        node = node[k]
    node[keys[-1]] = value


def expand_grid(grid: dict[str, list[Any]]) -> list[dict[str, Any]]:
    """Cross-product a {dotted_key: [values]} grid.

    Returns one override dict per combination, keys in the YAML's order.
    An empty grid yields a single empty override (the baseline arm).
    """
    if not grid:
        return [{}]
    for k, values in grid.items():
        if not isinstance(values, list):
            raise ValueError(f"grid[{k!r}] must be a list, got {type(values).__name__}")
    keys = list(grid.keys())
    combos = []
    for values in itertools.product(*(grid[k] for k in keys)):
        combos.append(dict(zip(keys, values)))
    return combos


def combo_slug(combo: dict[str, Any]) -> str:
    """Filesystem-safe slug for a combo: {"fed.mode": "iid"} -> "modeiid"."""
    if not combo:
        return "baseline"
    parts = []
    for k, v in combo.items():
        leaf = k.split(".")[-1]
        raw = f"{leaf}{v}"
        parts.append(re.sub(r"[^A-Za-z0-9.]+", "", raw.replace(".", "p")))
    return "_".join(parts)


def parse_seeds(text: str | None, fallback: list[int]) -> list[int]:
    """Parse ``--seeds 42,123`` (override) or fall back to the YAML list."""
    if not text:
        return list(fallback)
    seeds = [int(s) for s in str(text).replace(" ", "").split(",") if s]
    if not seeds:
        raise ValueError(f"--seeds {text!r} parsed to an empty list")
    return seeds


def write_run_config(
    base_cfg: dict[str, Any],
    overrides: dict[str, Any],
    seed: int,
    run_dir: Path,
    is_fed: bool,
) -> Path:
    """Materialize the per-run config: overrides + seed + isolated output paths.

    Central runs get ``checkpoint.dir: <run_dir>/checkpoints``; federated runs
    get ``output_dir: <run_dir>`` (best_global.pt / history.json land there),
    so grid arms never clobber each other's checkpoints.
    """
    cfg = copy.deepcopy(base_cfg)
    for dotted, value in overrides.items():
        set_dotted(cfg, dotted, value)
    cfg["seed"] = int(seed)
    if is_fed:
        set_dotted(cfg, "output_dir", str(run_dir))
    else:
        set_dotted(cfg, "checkpoint.dir", str(run_dir / "checkpoints"))
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / "config.yaml"
    with open(path, "w") as f:
        f.write("# Auto-generated by scripts/sweep_lib.py — do not edit.\n")
        yaml.safe_dump(cfg, f, sort_keys=False)
    return path


def run_cmd(cmd: list[str], log_path: Path, dry_run: bool) -> int:
    """Run a command, teeing stdout+stderr to ``log_path``. Returns exit code."""
    pretty = " ".join(str(c) for c in cmd)
    if dry_run:
        print(f"    $ {pretty}")
        return 0
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, "w") as log:
        log.write(f"$ {pretty}\n\n")
        log.flush()
        proc = subprocess.run(
            [str(c) for c in cmd], cwd=REPO_ROOT,
            stdout=log, stderr=subprocess.STDOUT,
        )
    return int(proc.returncode)


def eval_checkpoint(cfg_path: Path, is_fed: bool) -> Path:
    """Checkpoint that generate_and_eval should load after training."""
    if is_fed:
        return cfg_path.parent / "best_global.pt"
    return cfg_path.parent / "checkpoints" / "best.pt"


def collect_results(
    run_dir: Path,
    eval_dir: Path,
    requested: list[str],
    is_fed: bool,
) -> dict[str, Any]:
    """Merge eval metrics + requested sweep keys (+ fed server_loss) into a
    results dict. Missing keys become null rather than raising — a failed arm
    should still leave a results.json explaining itself."""
    metrics: dict[str, Any] = {}
    metrics_path = eval_dir / "metrics.json"
    if metrics_path.exists():
        try:
            metrics = json.loads(metrics_path.read_text()).get("metrics", {})
        except (json.JSONDecodeError, OSError):
            metrics = {}
    requested_out = {k: metrics.get(k) for k in requested}
    if "server_loss" in requested and requested_out["server_loss"] is None \
            and is_fed:
        history_path = run_dir / "history.json"
        if history_path.exists():
            try:
                history = json.loads(history_path.read_text())
                losses = [h["val"]["loss"] for h in history
                          if (h.get("val") or {}).get("loss") is not None]
                if losses:
                    requested_out["server_loss"] = min(losses)
            except (json.JSONDecodeError, OSError, KeyError, TypeError):
                pass
    return {"metrics": metrics, "requested": requested_out}


def python() -> str:
    """Interpreter: the venv running this script when there is one."""
    return sys.executable or "python"
